import Head from 'next/head'
import Link from 'next/link'
import { BsGithub, BsGoogle, BsTwitter } from 'react-icons/bs'

export default function LogIn() {
  return (
    <>
      <Head>
        <title>Trello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex justify-center items-center min-h-screen'>
        <section className='flex flex-col'>
          <form>
            <div>
              <h1 className='text-center text-4xl'>Welcome Back</h1>
            </div>
            <p className='text-center py-6'>Log in with</p>
            <div className='flex justify-center gap-12 py-2'>
              <BsGithub className='h-10 w-10 cursor-pointer' />
              <BsGoogle className='h-10 w-10 cursor-pointer' />
              <BsTwitter className='h-10 w-10 cursor-pointer' />
            </div>
            <p className='text-center pt-6 pb-4'>Or login with email</p>
            <div className='flex flex-col gap-2 pt-4'>
              <label>Email Adress</label>
              <input type='email' placeholder='Email Adress' className='py-2 px-2 rounded-lg' />
            </div>
            <div className='flex flex-col gap-2 pt-4'>
              <label>Password</label>
              <input type='password' placeholder='Password' className='py-2 px-2 rounded-lg' />
            </div>
            <div className='flex gap-10 pt-4'>
              <div className='flex gap-2'>
                <input type='checkbox' className='' />
                <label>Keep me loged in</label>
              </div>
              <div>
                <Link href='#' className='text-[#D8807D]'> Forget your password?</Link>
              </div>
            </div>
            <div className='pt-4'>
              <button className='w-full bg-[#138859] rounded-lg h-12'>Log In</button>
            </div>
          </form>
          <div className='pt-4'>
            <p>Dont have a account? <Link href='signup' className='text-[#D8807D]'> Sign up </Link> </p>
          </div>
        </section>
      </main>
    </>
  )
}
