import Head from 'next/head'
import Link from 'next/link'
import Swal from 'sweetalert2'

export default function SignUp() {

  const HandleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    Swal.fire({
      icon: 'success',
      text: 'A sua conta foi criada com sucesso',
      confirmButtonColor: '#D8807D'
    })
  }

  return (
    <>
      <Head>
        <title>Trello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex justify-center items-center min-h-screen'>
        <section className='flex flex-col'>
          <form className='w-96' onSubmit={(e) => HandleSubmit(e)}>
            <div>
              <h1 className='text-center text-4xl'>Sign Up</h1>
            </div>
            <div className='flex flex-col gap-2 pt-4'>
              <label>Name</label>
              <input type='text' placeholder='Your name' className='py-2 px-2 rounded-lg' />
            </div>
            <div className='flex flex-col gap-2 pt-4'>
              <label>Email Adress</label>
              <input type='email' placeholder='Email Adress' className='py-2 px-2 rounded-lg' />
            </div>
            <div className='flex flex-col gap-2 pt-4'>
              <label>Password</label>
              <input type='password' placeholder='Password' className='py-2 px-2 rounded-lg' />
            </div>
            <div className='flex flex-col gap-2 pt-4'>
              <label>Confirm your password</label>
              <input type='password' placeholder='Password' className='py-2 px-2 rounded-lg' />
            </div>
            <div className='flex flex-col gap-2 pt-4'>
              <label >Insert a photo</label>
              <input type='text' placeholder='Insert a url' className='py-2 px-2 rounded-lg' />
              <p className='text-center py-2'>Or</p>
              <input type='text' placeholder='Future drag-and-drop' className='py-2 px-2 rounded-lg' />
            </div>
            <div className='pt-8'>
              <button className='w-full bg-[#138859] rounded-lg h-12 '>Create a accont</button>
            </div>
          </form>
        </section>
      </main>
    </>
  )
}
